config/routes.rb
Rails.application.routes.draw do
  root :to => 'flights#index'
  resources :seats
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/flight.rb
class Flight < ApplicationRecord

  belongs_to :airplane, :optional => true
  has_many :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
    respond_to do |format|
        format.html { @flights = Flight.all }
        format.json { render :json => @flights.to_json(:include => :airplane) }
    end


  end

  # GET /flights/1
  # GET /flights/1.json
  def show
    @flight = Flight.find params[:id]
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
    @flight = Flight.find params[:id]
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to flights_path, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to flights_path, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def flight_params
      params.require(:flight).permit(:flight_number, :origin, :destination)
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # def flight_params
    #   params.fetch(:flight, {})
    # end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for @flight, :class => "form-horizontal" do |f| %>
<fieldset class="form-group">
  <%= f.label :flight_number %>
  <%= f.text_field :flight_number, :class => "form-control"  %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :origin %>
  <%=  f.text_field :origin, :class => "form-control" %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :destination %>
  <%= f.text_field :destination, :class => "form-control"  %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :date %>
  <%= f.text_field :date, :class => "form-control"  %>
</fieldset>

<fieldset>
  <label></label>
  <%= f.submit %>
</fieldset>

<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form', flight: @flight %>

<!-- <%= link_to 'Show', @flight %> | -->
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flights Information</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><b> ORIGIN </b></td><td><b> DESTINATION </b></td><td> <b>FLIGHT NO </b></td>
    </tr>
    <li ></li>

    <% @flights.each do |flight| %>
      <tr>
     <td><%= flight.origin %></td><td><%= flight.destination %></td><td><%= flight.flight_number %></td><td><%= link_to 'SHOW',flight %></td><td> <%= link_to 'EDIT', edit_flight_path(flight) %></td><td><%= link_to 'Destroy', flight, method: :delete, data:{comfirm:'Are you sure?'} %></td>
      </tr>
    <% end %>

  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form', flight: @flight %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @flight.flight_number  %></h1>
  <h3>Origin: <%= @flight.origin %></h3>
  <h3>Destination: <%= @flight.destination %></h3>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>