config/routes.rb
Rails.application.routes.draw do
  root :to => 'flights#index'
  resources :seats
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airplane.rb
class Airplane < ApplicationRecord

  has_many :flights
  has_many :reservations, :through => :flights
end

app/controllers/airplanes_controller.rb
class AirplanesController < ApplicationController
  before_action :set_airplane, only: [:show, :edit, :update, :destroy]

  # GET /airplanes
  # GET /airplanes.json
  def index
    @airplanes = Airplane.all
  end

  # GET /airplanes/1
  # GET /airplanes/1.json
  def show
    @airplane = Airplane.find params[:id]
  end

  # GET /airplanes/new
  def new
    @airplane = Airplane.new
  end

  # GET /airplanes/1/edit
  def edit
    @airplane = Airplane.find params[:id]
  end

  # POST /airplanes
  # POST /airplanes.json
  def create
    @airplane = Airplane.new (airplane_params)

    respond_to do |format|
      if @airplane.save
        format.html { redirect_to @airplane, notice: 'Airplane was successfully created.' }
        format.json { render :show, status: :created, location: @airplane }
      else
        format.html { render :new }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airplanes/1
  # PATCH/PUT /airplanes/1.json
  def update
    respond_to do |format|
      if @airplane.update(airplane_params)
        format.html { redirect_to @airplane, notice: 'Airplane was successfully updated.' }
        format.json { render :show, status: :ok, location: @airplane }
      else
        format.html { render :edit }
        format.json { render json: @airplane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airplanes/1
  # DELETE /airplanes/1.json
  def destroy
    @airplane.destroy
    respond_to do |format|
      format.html { redirect_to airplanes_url, notice: 'Airplane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private


    def airplane_params
      params.require(:airplane).permit(:name, :row, :column)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_airplane
      @airplane = Airplane.find(params[:id])
    end

    # # Never trust parameters from the scary internet, only allow the white list through.
    # def airplane_params
    #   params.fetch(:airplane, {})
    # end
end

app/helpers/airplanes_helper.rb
module AirplanesHelper
end

app/views/airplanes/_form.html.erb
<%= form_for @airplane, :class => "form-horizontal" do |f| %>
<fieldset class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control"  %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :row %>
  <%=  f.text_field :row, :class => "form-control" %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :column %>
  <%= f.text_field :column, :class => "form-control"  %>
</fieldset>


<fieldset>
  <label></label>
  <%= f.submit %>
</fieldset>

<% end %>

app/views/airplanes/edit.html.erb
<h1>Editing Airplane</h1>

<%= render 'form', airplane: @airplane %>

<%= link_to 'Show', @airplane %> |
<%= link_to 'Back', airplanes_path %>

app/views/airplanes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airplanes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td>NAME</td><td>ROW</td><td>COLUMN</td>
    </tr>
    <% @airplanes.each do |airplane| %>
        <tr>
        <td> <%=  airplane.name %> </td><td><%= airplane.row %></td><td><%= airplane.column %></td><td><%= link_to ' Show ', airplane %></td><td><%= link_to 'Edit ', edit_airplane_path(airplane) %></td><td><%= link_to 'Destroy', airplane, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Airplane', new_airplane_path %>

app/views/airplanes/new.html.erb
<h1>New Airplane</h1>

<%= render 'form', airplane: @airplane %>
<!-- <%= render :partial => 'form' %> -->

<%= link_to 'Back', airplanes_path %>

app/views/airplanes/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @airplane.name  %></h1>
<h3>Row: <%= @airplane.row %></h3>
<h3>Column: <%= @airplane.column %></h3>


<%= link_to 'Edit', edit_airplane_path(@airplane) %> |
<%= link_to 'Back', airplanes_path %>