config/routes.rb
Rails.application.routes.draw do
  root :to => 'flights#index'
  resources :seats
  resources :reservations
  resources :users
  resources :flights
  resources :airplanes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reservation.rb
class Reservation < ApplicationRecord

  belongs_to :user, :optional => true
  belongs_to :flight, :optional => true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_reservation, only: [:show, :edit, :update, :destroy]

  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all
      respond_to do |format|
          format.html { @reservations = User.first.reservations }
          format.json { render :json => User.first.reservations.to_json(:include => {
            :flight => @flight,
            :user => @user
            }) }
          # format.json { render :json => @reservations.to_json(:include => :flight ) }
      end
  end

  #
  # def index
  #   @flights = Flight.all
  #   respond_to do |format|
  #       format.html { @flights = Flight.all }
  #       format.json { render :json => @flights.to_json(:include => :airplane) }
  #   end
  #
  #
  # GET /reservations/1
  # GET /reservations/1.json
  def show
  end

  # GET /reservations/new
  def new
    @reservation = Reservation.new
  end

  # GET /reservations/1/edit
  def edit
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(reservation_params)

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to @reservation, notice: 'Reservation was successfully created.' }
        format.json { render :show, status: :created, location: @reservation }
      else
        format.html { render :new }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservations/1
  # PATCH/PUT /reservations/1.json
  def update
    respond_to do |format|
      if @reservation.update(reservation_params)
        format.html { redirect_to @reservation, notice: 'Reservation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reservation }
      else
        format.html { render :edit }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation.destroy
    respond_to do |format|
      format.html { redirect_to reservations_url, notice: 'Reservation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def reservation_params
      params.require(:reservation).permit(:user_id,:flight_id,:seat_row_col)
    end

    def set_reservation
      @reservation = Reservation.find(params[:id])
    end

  end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for @reservation, :class => "form-horizontal" do |f| %>
<fieldset class="form-group">
  <%= f.label :user_id, :as => "User ID"%>
  <%= f.text_field :user_id, :class => "form-control"  %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :flight_id, :as =>'Flight ID' %>
  <%= f.text_field :flight_id, :class => "form-control"  %>
</fieldset>
<fieldset class="form-group">
  <%= f.label :seat_row_col %>
  <%= f.text_field :seat_row_col, :class => "form-control"  %>
</fieldset>

  <label></label>
  <%= f.submit %>
</fieldset>

<% end %>

app/views/reservations/edit.html.erb
<h1>Editing Reservation</h1>

<%= render 'form', reservation: @reservation %>

<%= link_to 'Show', @reservation %> |
<%= link_to 'Back', reservations_path %>

app/views/reservations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>User Name:</td><td>Flight Number:</td><td>Airplane</td><td>Seat Number</td>
      </tr>
    <% @reservations.each do |reservation| %>

        <td><%=reservation.user.name %></td>
        <td><%=reservation.flight.flight_number %></td>
        <td><%=reservation.flight.airplane.name%></td>
        <td><%=reservation.seat_row_col  %></td>
        <td><%= link_to 'Show', reservation %></td>
        <td><%= link_to 'Edit', edit_reservation_path(reservation) %></td>
        <td><%= link_to 'Destroy', reservation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reservation', new_reservation_path %>

app/views/reservations/new.html.erb
<h1>New Reservation</h1>


<%= render 'form', reservation: @reservation %>

<%= link_to 'Back', reservations_path %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>